# Generated by Django 5.2.6 on 2025-10-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags_text', models.CharField(blank=True, max_length=500)),
                ('has_custom_thumbnail', models.BooleanField(default=False)),
                ('in_playlists', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('entities', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
